import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1c1c',
        'surface': '#f9f9f9',
        'on-surface-variant': '#404944',
        'background': '#f9f9f9',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#474747',
        'secondary': '#5e5e5e',
        'on-tertiary-fixed-variant': '#6b3836',
        'tertiary-fixed-dim': '#fcb4b0',
        'inverse-primary': '#9ed2b9',
        'secondary-fixed-dim': '#c6c6c6',
        'primary-container': '#1a4d3a',
        'on-secondary-container': '#646464',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#360e0e',
        'surface-dim': '#dadada',
        'surface-container': '#eeeeee',
        'on-background': '#1a1c1c',
        'tertiary-container': '#683634',
        'on-primary-container': '#89bda4',
        'on-error': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'secondary-fixed': '#e2e2e2',
        'on-secondary-fixed': '#1b1b1b',
        'surface-container-highest': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'primary': '#003625',
        'outline': '#717974',
        'inverse-surface': '#2f3131',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#002115',
        'inverse-on-surface': '#f1f1f1',
        'primary-fixed': '#b9eed4',
        'surface-variant': '#e2e2e2',
        'on-error-container': '#93000a',
        'secondary-container': '#e2e2e2',
        'surface-bright': '#f9f9f9',
        'tertiary': '#4d201f',
        'on-tertiary-container': '#e5a09c',
        'primary-fixed-dim': '#9ed2b9',
        'surface-tint': '#366853',
        'error': '#ba1a1a',
        'outline-variant': '#c0c9c2',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdad7',
        'on-primary-fixed-variant': '#1d4f3c',
        'surface-container-low': '#f3f3f3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 30s linear infinite',
      },
    },
  },
  plugins: [],
}

export default config
